### PR TITLE
ticket 7 ready for review

### PR DESCRIPTION
**Pull request by dimopapa91**
Hey ticket 7 is ready to review! Thanks!

### CODE REVIEW

**Review by EddTheDuck — CHANGES_REQUESTED** [review]
The vote system you have implemented isn't quite working as intended.

Currently I can upvote and downvote more than once.

Please implement a feature that doesn't allow this behavhiour.

Thanks

**Review by johnhutcheon — CHANGES_REQUESTED** [review]
Hey Dimos, think you're nearly there! Thanks for implementing Edd's feedback, but at the moment if you click to up vote an article, then you refresh the page, the vote isn't there. It works for the down votes, but the up votes just needs a little bit of work. 👍

**Review by johnhutcheon — APPROVED** [review]
Thanks for making the change, all good to merge now 🙂

**Comment by dimopapa91** [comment]
Thanks for that! -.^

**Pull request merged**
